"""
NAVIDOOR - Indian Context & Accessibility Label Mappings
Provides typical real-world physical heights (meters) for accurate distance estimation,
risk categories, and regional Indian language names for detected items.
"""

# Real-world physical heights in meters for pinhole camera distance estimation
OBJECT_REAL_HEIGHTS_METERS = {
    'person': 1.70,
    'bicycle': 1.00,
    'car': 1.50,
    'motorcycle': 1.10,
    'airplane': 4.00,
    'bus': 3.20,
    'train': 3.80,
    'truck': 2.80,
    'boat': 2.00,
    'traffic light': 1.20,
    'fire hydrant': 0.75,
    'stop sign': 0.75,
    'parking meter': 1.20,
    'bench': 0.85,
    'bird': 0.25,
    'cat': 0.30,
    'dog': 0.60,      # Stray dog / Indian pariah dog
    'horse': 1.60,
    'sheep': 0.90,
    'cow': 1.50,      # Stray cow on Indian roads
    'elephant': 2.80,
    'bear': 1.50,
    'zebra': 1.40,
    'giraffe': 4.50,
    'backpack': 0.50,
    'umbrella': 0.85,
    'handbag': 0.35,
    'tie': 0.45,
    'suitcase': 0.70,
    'frisbee': 0.05,
    'skis': 1.60,
    'snowboard': 1.50,
    'sports ball': 0.22,
    'kite': 0.60,
    'baseball bat': 0.85,
    'baseball glove': 0.30,
    'skateboard': 0.15,
    'surfboard': 1.80,
    'tennis racket': 0.70,
    'bottle': 0.22,   # Pill bottle / water bottle
    'wine glass': 0.20,
    'cup': 0.12,
    'fork': 0.18,
    'knife': 0.20,
    'spoon': 0.15,
    'bowl': 0.10,
    'banana': 0.18,
    'apple': 0.08,
    'sandwich': 0.08,
    'orange': 0.08,
    'broccoli': 0.15,
    'carrot': 0.18,
    'hot dog': 0.06,
    'pizza': 0.04,
    'donut': 0.05,
    'cake': 0.15,
    'chair': 0.85,
    'couch': 0.85,
    'potted plant': 0.60,
    'bed': 0.65,
    'dining table': 0.75,
    'toilet': 0.75,
    'tv': 0.65,
    'laptop': 0.25,
    'mouse': 0.04,
    'remote': 0.18,
    'keyboard': 0.03,
    'cell phone': 0.15,
    'microwave': 0.35,
    'oven': 0.85,
    'toaster': 0.20,
    'sink': 0.85,
    'refrigerator': 1.75,
    'book': 0.24,
    'clock': 0.30,
    'vase': 0.30,
    'scissors': 0.18,
    'teddy bear': 0.35,
    'hair drier': 0.22,
    'toothbrush': 0.18,
    # Custom accessibility & Indian Infrastructure markers
    'door': 2.10,
    'stairs': 0.50,
    'ramp': 0.30,
    'elevator': 2.20,
    'escalator': 2.50,
    'pole': 2.50,
    'pothole': 0.15,
    'water_puddle': 0.05,
    'manhole': 0.10,
    'medicine_box': 0.12,
    'medicine_strip': 0.10,
    'auto_rickshaw': 1.75,
}

# Category priority for voice alert announcements (Higher number = higher alert urgency)
CLASS_PRIORITY = {
    'person': 9,
    'car': 10,
    'bus': 10,
    'motorcycle': 10,
    'auto_rickshaw': 10,
    'bicycle': 8,
    'dog': 7,
    'stairs': 10,
    'pothole': 10,
    'manhole': 10,
    'water_puddle': 8,
    'pole': 9,
    'door': 8,
    'chair': 6,
    'dining table': 6,
    'medicine_box': 7,
    'medicine_strip': 7,
    'bottle': 6,
}

# Regional Indian Language Translations
TRANSLATIONS = {
    'en': {
        'person': 'Person',
        'car': 'Car',
        'bus': 'Bus',
        'motorcycle': 'Motorcycle',
        'auto_rickshaw': 'Auto Rickshaw',
        'bicycle': 'Bicycle',
        'dog': 'Dog',
        'cow': 'Cow',
        'stairs': 'Stairs',
        'door': 'Door',
        'pole': 'Pole',
        'pothole': 'Pothole',
        'water_puddle': 'Water puddle',
        'chair': 'Chair',
        'bottle': 'Bottle',
        'medicine': 'Medicine',
        'ahead': 'ahead',
        'on_your_left': 'on your left',
        'on_your_right': 'on your right',
        'directly_ahead': 'directly ahead',
        'clear_left': 'Path is clear on your left.',
        'clear_right': 'Path is clear on your right.',
        'step_back': 'Warning: Please step back.',
        'safe_path': 'Clear walking path directly ahead.',
    },
    'hi': {
        'person': 'व्यक्ति',
        'car': 'गाड़ी',
        'bus': 'बस',
        'motorcycle': 'मोटरसाइकिल',
        'auto_rickshaw': 'ऑटो रिक्शा',
        'bicycle': 'साइकिल',
        'dog': 'कुत्ता',
        'cow': 'गाय',
        'stairs': 'सीढ़ियां',
        'door': 'दरवाजा',
        'pole': 'खंभा',
        'pothole': 'गड्ढा',
        'water_puddle': 'पानी का गड्ढा',
        'chair': 'कुर्सी',
        'bottle': 'बोतल',
        'medicine': 'दवाई',
        'ahead': 'आगे',
        'on_your_left': 'बाईं ओर',
        'on_your_right': 'दाईं ओर',
        'directly_ahead': 'बिल्कुल सामने',
        'clear_left': 'बाईं ओर रास्ता साफ है।',
        'clear_right': 'दाईं ओर रास्ता साफ है।',
        'step_back': 'सावधान: कृपया पीछे हटें।',
        'safe_path': 'सामने रास्ता बिल्कुल साफ है।',
    },
    'mr': {
        'person': 'व्यक्ती',
        'car': 'गाडी',
        'bus': 'बस',
        'motorcycle': 'मोटारसायकल',
        'auto_rickshaw': 'रिक्षा',
        'bicycle': 'सायकल',
        'dog': 'कुत्रा',
        'cow': 'गाय',
        'stairs': 'पायऱ्या',
        'door': 'दार',
        'pole': 'खांब',
        'pothole': 'खड्डा',
        'water_puddle': 'पाण्याचे डबके',
        'chair': 'खुर्ची',
        'bottle': 'बाटली',
        'medicine': 'औषध',
        'ahead': 'पुढे',
        'on_your_left': 'डाव्या बाजूस',
        'on_your_right': 'उजव्या बाजूस',
        'directly_ahead': 'अगदी समोर',
        'clear_left': 'डाव्या बाजूने वाट मोकळी आहे.',
        'clear_right': 'उजव्या बाजूने वाट मोकळी आहे.',
        'step_back': 'सावधान: मागे व्हा.',
        'safe_path': 'समोर चालण्यासाठी वाट मोकळी आहे.',
    }
}
